name: Deploy Larris Github Showcase via FTP

on:
  push:
    branches:
      - main  # Change if needed

jobs:
  deploy:
    name: 🚀 Deploy via FTP
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Checkout Repository
        uses: actions/checkout@v4

      - name: 📤 Deploy to FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.2
        with:
          server: ${{ secrets.FTP_HOST }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          server-dir: ${{ secrets.FTP_PATH }}
          local-dir: ./   # Deploy everything from repo root
          exclude: |
            **/.git/**
            **/.github/**
            **/node_modules/**
            **/*.md
            **/.gitignore
